### PR TITLE
Dependency updates

### PR DESCRIPTION
**Pull request by agramian**
Updates `gradle`, `buildToolsVersion`,  `support` library, `rxjava`, and `play-services-location` dependency versions to latest and bumped `RxLocation` version numbers.

### CODE REVIEW

**Comment by patloew** [comment]
Thank you for the pull request. However, Gradle chooses the newest version on conflicts (e.g. when the user of the library declares a newer version in their `build.gradle`), therefore a new library version for dependency updates is not needed.

**Comment by agramian** [comment]
@patloew I don't believe that is the case.  Here is a screenshot of the warning I am seeing when explicitly declaring `compile 'com.google.android.gms:play-services-maps:$10.0.1'` in my `build.gradle` file.

screen shot 2017-01-07 at 11 19 21 am

If you do not want to update the versions then it would be helpful to add a note in your readme to declare the `RxLocation` dependency like this:

```
compile 'com.google.android.gms:play-services-maps:10.0.1'
compile('com.patloew.rxlocation:rxlocation:1.0.1') {
    exclude group: 'com.google.android.gms'
}
```

**Comment by agramian** [comment]
Never mind this was my mistake.  I was not explicitly declaring the location dependency.  `RxLocation` does not include maps so that was not the issue.

This works fine:
```
compile 'com.google.android.gms:play-services-location:10.0.1'
compile 'com.patloew.rxlocation:rxlocation:1.0.1'
```

**Comment by samus** [comment]
Just a note, this bit me too.  If it was in the readme I wouldn't be commenting here. :-)

**Comment by patloew** [comment]
Added a note in the readme.

**Pull request closed without merging**
